FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        g++ \
        make \
        ca-certificates \
        python3 \
        iproute2 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
